const express = require('express');
const fetch = require('node-fetch');
const app = express();
const PORT = process.env.PORT || 3000;

const API_FOOTBALL_KEY = process.env.API_FOOTBALL_KEY || '';
const NEWS_API_KEY = process.env.NEWS_API_KEY || '';
const OPENWEATHER_KEY = process.env.OPENWEATHER_KEY || '';
const THESPORTSDB_KEY = process.env.THESPORTSDB_KEY || '123';
const SPORTMONKS_KEY = process.env.SPORTMONKS_KEY || '';
const FOOTBALL_DATA_KEY = process.env.FOOTBALL_DATA_KEY || '';
const ODDS_API_KEY = process.env.ODDS_API_KEY || '';

app.use(express.static('public'));

const ESPN_LEAGUES = [
  ['bra.1','Brasileirão Série A'],['bra.2','Brasileirão Série B'],['conmebol.libertadores','Libertadores'],['conmebol.sudamericana','Sul-Americana'],
  ['eng.1','Premier League'],['esp.1','La Liga'],['ita.1','Serie A Itália'],['ger.1','Bundesliga'],['fra.1','Ligue 1'],['ned.1','Eredivisie'],['nor.1','Noruega'],['por.1','Portugal'],['ksa.1','Saudita']
].map(([key,name])=>({key,name}));

const CONTEXT = {
  rivalries: [['Palmeiras','Corinthians'],['Palmeiras','Santos'],['São Paulo','Santos'],['São Paulo','Corinthians'],['Athletico-PR','Coritiba'],['Athletico Paranaense','Coritiba'],['Flamengo','Fluminense'],['Flamengo','Vasco'],['Grêmio','Internacional'],['Atlético-MG','Cruzeiro'],['Barcelona','Real Madrid'],['Liverpool','Everton'],['Manchester United','Manchester City']],
  notes: [['Always Ready','em casa costuma ter vantagem pela altitude de El Alto'],['Bolívar','em casa costuma ter vantagem pela altitude de La Paz'],['The Strongest','em casa costuma ter vantagem pela altitude de La Paz'],['LDU Quito','joga em altitude relevante em Quito'],['Bodo/Glimt','costuma ser equipe forte/ofensiva no contexto da Noruega'],['Athletico-PR','costuma ter força importante como mandante'],['Atlético-MG','em casa costuma aumentar intensidade em jogos decisivos'],['Fluminense','em casa costuma assumir mais posse e pressão em Libertadores']],
  pressureKeywords: ['pressão','pressionado','demissão','cobrado','crise','precisa vencer','obrigação','decisivo','mata-mata','final','rebaixamento'],
  winNeedKeywords: ['precisa vencer','obrigação de vencer','decisivo','mata-mata','rebaixamento','classificação','vaga','eliminado']
};

const isoDate = d => String(d || new Date().toISOString().slice(0,10));
const yyyymmdd = d => isoDate(d).replaceAll('-','');
const norm = s => String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const gameKey = (h,a) => norm(h)+'_'+norm(a);
const num = v => { const n = Number(String(v ?? '').replace('%','').trim()); return isNaN(n) ? 0 : n; };
const avg = arr => arr.length ? arr.reduce((a,b)=>a+b,0)/arr.length : 0;
async function fetchJson(url, options={}){ const res=await fetch(url,options); if(!res.ok) throw new Error('HTTP '+res.status); return res.json(); }
async function apiFootball(path){ if(!API_FOOTBALL_KEY) throw new Error('API_FOOTBALL_KEY não configurada'); return fetchJson('https://v3.football.api-sports.io'+path,{headers:{'x-apisports-key':API_FOOTBALL_KEY,'Accept':'application/json'}}); }
async function safeApiFootball(path){ try{return await apiFootball(path)}catch(e){return {response:[],error:String(e.message||e)}} }
async function espn(path){ return fetchJson('https://site.api.espn.com/apis/site/v2/sports/soccer/'+path,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json,text/plain,*/*'}}); }
function normalizeApiGame(m){ const f=m.fixture||{},l=m.league||{},t=m.teams||{},g=m.goals||{},s=f.status||{}; const short=s.short||''; const live=['1H','2H','HT','ET','BT','P','SUSP','INT','LIVE'].includes(short); const finished=['FT','AET','PEN'].includes(short); return {source:'API-Football',id:String(f.id||''),fixtureId:f.id||'',leagueId:l.id||'',season:l.season||'',league:l.name||'',date:f.date||'',venue:f.venue?.name||'',city:f.venue?.city||'',time:f.date?new Date(f.date).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'',status:s.long||short||'',state:live?'in':finished?'post':'pre',live,minute:s.elapsed?String(s.elapsed)+"'":'',home:{id:t.home?.id||'',name:t.home?.name||'',logo:t.home?.logo||'',score:g.home??''},away:{id:t.away?.id||'',name:t.away?.name||'',logo:t.away?.logo||'',score:g.away??''}}; }
function normalizeEspnGame(event,league){ const comp=event.competitions?.[0]||{}; const competitors=comp.competitors||[]; const home=competitors.find(c=>c.homeAway==='home')||competitors[0]||{}; const away=competitors.find(c=>c.homeAway==='away')||competitors[1]||{}; const type=event.status?.type||{}; return {source:'ESPN',id:event.id,fixtureId:'',leagueId:'',season:'',leagueKey:league.key,league:league.name,date:event.date||'',venue:comp.venue?.fullName||'',city:comp.venue?.address?.city||'',time:event.date?new Date(event.date).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'',status:type.description||type.detail||type.name||'',state:type.state||'',live:type.state==='in',minute:event.status?.displayClock||'',home:{id:'',name:home.team?.displayName||home.team?.name||'',logo:home.team?.logo||'',score:home.score??''},away:{id:'',name:away.team?.displayName||away.team?.name||'',logo:away.team?.logo||'',score:away.score??''}}; }

app.get('/api/health',(req,res)=>res.json({ok:true,providers:{apiFootball:!!API_FOOTBALL_KEY,newsApi:!!NEWS_API_KEY,openWeather:!!OPENWEATHER_KEY,theSportsDb:!!THESPORTSDB_KEY,sportMonks:!!SPORTMONKS_KEY,footballData:!!FOOTBALL_DATA_KEY,oddsApi:!!ODDS_API_KEY,espn:true}}));
app.get('/api/games',async(req,res)=>{ const date=isoDate(req.query.date); const out=[],errors=[]; try{ const apiData=await apiFootball(`/fixtures?date=${date}`); (apiData.response||[]).forEach(m=>out.push(normalizeApiGame(m))); }catch(e){errors.push({source:'API-Football',error:String(e.message||e)})} await Promise.all(ESPN_LEAGUES.map(async league=>{try{const data=await espn(`${league.key}/scoreboard?dates=${yyyymmdd(date)}&limit=200`); (data.events||[]).forEach(ev=>out.push(normalizeEspnGame(ev,league)));}catch(e){errors.push({source:'ESPN',league:league.name,error:String(e.message||e)})}})); const map=new Map(); for(const g of out){const key=gameKey(g.home.name,g.away.name); if(!key||key==='_') continue; const old=map.get(key); if(!old) map.set(key,g); else if(g.source==='API-Football') map.set(key,{...old,...g});} res.json({ok:true,date,total:map.size,games:[...map.values()].sort((a,b)=>new Date(a.date)-new Date(b.date)),errors}); });

function normalizeStats(resp){ const rows=[]; (resp||[]).forEach(tb=>{const team=tb.team?.name||''; (tb.statistics||[]).forEach(s=>rows.push({team,label:String(s.type||''),value:s.value??''}));}); return rows; }
function normalizeEvents(events){ return (events||[]).map(e=>({minute:e.time?.elapsed?String(e.time.elapsed)+"'":'',team:e.team?.name||'',player:e.player?.name||'',type:e.type||'',detail:e.detail||''})); }
function splitByTeam(stats){ const teams=[...new Set(stats.map(s=>s.team).filter(Boolean))]; const home=teams[0]||'Casa',away=teams[1]||'Fora'; const homeStats={},awayStats={}; stats.forEach(s=>{(s.team===home?homeStats:awayStats)[String(s.label).toLowerCase()]=s.value}); return {home,away,homeStats,awayStats}; }
function find(obj,labels){ const k=Object.keys(obj).find(k=>labels.some(l=>k.includes(l))); return k?obj[k]:''; }
async function getTeamRecent(teamId,venue,last=10){ if(!teamId)return []; const data=await safeApiFootball(`/fixtures?team=${teamId}&last=${last}`); return (data.response||[]).filter(f=>{if(!venue)return true; const isHome=f.teams?.home?.id==teamId; return venue==='home'?isHome:!isHome;}).slice(0,last); }
function teamRecentSummary(fixtures,teamId){ const games=fixtures.map(f=>{const isHome=f.teams?.home?.id==teamId; const gf=isHome?f.goals?.home:f.goals?.away; const ga=isHome?f.goals?.away:f.goals?.home; return {gf:num(gf),ga:num(ga),win:num(gf)>num(ga),draw:num(gf)===num(ga),loss:num(gf)<num(ga)};}); return {played:games.length,wins:games.filter(g=>g.win).length,draws:games.filter(g=>g.draw).length,losses:games.filter(g=>g.loss).length,goalsForAvg:Number(avg(games.map(g=>g.gf)).toFixed(2)),goalsAgainstAvg:Number(avg(games.map(g=>g.ga)).toFixed(2))}; }
async function getH2H(homeId,awayId){ if(!homeId||!awayId)return []; const data=await safeApiFootball(`/fixtures/headtohead?h2h=${homeId}-${awayId}&last=10`); return data.response||[]; }
async function getStandings(leagueId,season){ if(!leagueId||!season)return []; const data=await safeApiFootball(`/standings?league=${leagueId}&season=${season}`); return data.response?.[0]?.league?.standings?.[0]||[]; }
async function getTeamSeasonStats(teamId,leagueId,season){ if(!teamId||!leagueId||!season)return null; const data=await safeApiFootball(`/teams/statistics?team=${teamId}&league=${leagueId}&season=${season}`); return data.response||null; }
async function getPlayerSeasonStats(teamId,leagueId,season){ if(!teamId||!leagueId||!season)return []; const data=await safeApiFootball(`/players?team=${teamId}&league=${leagueId}&season=${season}`); return data.response||[]; }
function standingOf(standings,teamId){ return standings.find(s=>s.team?.id==teamId)||null; }
async function newsContext(game){ if(!NEWS_API_KEY)return {items:[],base:[],pressureHome:false,pressureAway:false,needHome:false,needAway:false}; try{ const q=encodeURIComponent(`"${game.home.name}" "${game.away.name}" futebol OR soccer`); const data=await fetchJson(`https://newsapi.org/v2/everything?q=${q}&language=pt&sortBy=publishedAt&pageSize=8&apiKey=${NEWS_API_KEY}`); const items=(data.articles||[]).slice(0,8).map(a=>({title:a.title||'',source:a.source?.name||'',url:a.url||''})); const all=items.map(i=>i.title.toLowerCase()).join(' '); const homeN=norm(game.home.name),awayN=norm(game.away.name); const pressureWords=CONTEXT.pressureKeywords.some(k=>all.includes(k)); const needWords=CONTEXT.winNeedKeywords.some(k=>all.includes(k)); return {items,base:items.slice(0,4).map(a=>`Notícia: ${a.title} (${a.source||'fonte'})`),pressureHome:pressureWords&&all.includes(homeN.slice(0,5)),pressureAway:pressureWords&&all.includes(awayN.slice(0,5)),needHome:needWords&&all.includes(homeN.slice(0,5)),needAway:needWords&&all.includes(awayN.slice(0,5))}; }catch(e){return {items:[],base:[],pressureHome:false,pressureAway:false,needHome:false,needAway:false};} }
async function weatherContext(game){ if(!OPENWEATHER_KEY||!game.city)return {base:[],data:null}; try{ const q=encodeURIComponent(game.city); const data=await fetchJson(`https://api.openweathermap.org/data/2.5/weather?q=${q}&appid=${OPENWEATHER_KEY}&units=metric&lang=pt_br`); const desc=data.weather?.[0]?.description||''; const temp=Math.round(data.main?.temp||0); const wind=data.wind?.speed||0; return {data:{city:game.city,desc,temp,wind},base:[`Clima em ${game.city}: ${desc}, ${temp}°C, vento ${wind} m/s.`]}; }catch(e){return {base:[],data:null};} }
function internalNotes(game){ const home=game?.home?.name||'',away=game?.away?.name||''; const notes=[]; let homeBoost=0,awayBoost=0; const rivalry=CONTEXT.rivalries.some(([a,b])=>(norm(a)===norm(home)&&norm(b)===norm(away))||(norm(a)===norm(away)&&norm(b)===norm(home))); if(rivalry)notes.push('Clássico/rivalidade detectado: confiança reduzida.'); for(const [team,note] of CONTEXT.notes){ if(norm(team)===norm(home)){notes.push(`${team}: ${note}.`);homeBoost+=8;} if(norm(team)===norm(away)){notes.push(`${team}: ${note}.`);awayBoost+=8;} } return {rivalry,notes,homeBoost,awayBoost}; }
function makePregame(game,ctx){ const home=game.home?.name||'Mandante',away=game.away?.name||'Visitante'; const base=[],reasonsHome=[],reasonsAway=[]; let homeScore=0,awayScore=0,evidence=0; if(ctx.homeRecent.played>=3&&ctx.awayRecent.played>=3){evidence++; const hPts=ctx.homeRecent.wins*3+ctx.homeRecent.draws,aPts=ctx.awayRecent.wins*3+ctx.awayRecent.draws; homeScore+=hPts;awayScore+=aPts;base.push(`Forma recente: ${home} ${ctx.homeRecent.wins}V/${ctx.homeRecent.draws}E/${ctx.homeRecent.losses}D; ${away} ${ctx.awayRecent.wins}V/${ctx.awayRecent.draws}E/${ctx.awayRecent.losses}D.`); if(hPts>aPts)reasonsHome.push('melhor forma recente'); if(aPts>hPts)reasonsAway.push('melhor forma recente');}
 if(ctx.homeHomeRecent.played>=2&&ctx.awayAwayRecent.played>=2){evidence++; const hPts=ctx.homeHomeRecent.wins*3+ctx.homeHomeRecent.draws,aPts=ctx.awayAwayRecent.wins*3+ctx.awayAwayRecent.draws; homeScore+=hPts*1.25;awayScore+=aPts*1.15;base.push(`Casa/fora: ${home} em casa ${ctx.homeHomeRecent.wins}V/${ctx.homeHomeRecent.draws}E/${ctx.homeHomeRecent.losses}D; ${away} fora ${ctx.awayAwayRecent.wins}V/${ctx.awayAwayRecent.draws}E/${ctx.awayAwayRecent.losses}D.`); if(hPts>=aPts)reasonsHome.push('força como mandante'); if(aPts>hPts)reasonsAway.push('bom desempenho fora');}
 if(ctx.homeStanding&&ctx.awayStanding){evidence++; const hRank=num(ctx.homeStanding.rank),aRank=num(ctx.awayStanding.rank); homeScore+=Math.max(0,25-hRank);awayScore+=Math.max(0,25-aRank);base.push(`Tabela: ${home} está em ${hRank}º; ${away} está em ${aRank}º.`); if(hRank&&aRank&&hRank<aRank)reasonsHome.push('melhor posição na tabela'); if(hRank&&aRank&&aRank<hRank)reasonsAway.push('melhor posição na tabela');}
 if(ctx.h2h.length>=3){evidence++; let hw=0,aw=0,d=0; ctx.h2h.forEach(f=>{const hId=f.teams?.home?.id,wh=f.teams?.home?.winner,wa=f.teams?.away?.winner; if(wh===true){if(hId==game.home.id)hw++;else aw++;}else if(wa===true){if(hId==game.home.id)aw++;else hw++;}else d++;}); homeScore+=hw*2+d;awayScore+=aw*2+d;base.push(`H2H recente: ${home} ${hw} vitória(s), ${away} ${aw} vitória(s), ${d} empate(s).`); if(hw>aw)reasonsHome.push('H2H recente favorável'); if(aw>hw)reasonsAway.push('H2H recente favorável');}
 if(ctx.homeSeasonStats&&ctx.awaySeasonStats){evidence++; const hg=num(ctx.homeSeasonStats.goals?.for?.total?.total),ag=num(ctx.awaySeasonStats.goals?.for?.total?.total),hga=num(ctx.homeSeasonStats.goals?.against?.total?.total),aga=num(ctx.awaySeasonStats.goals?.against?.total?.total); homeScore+=hg*.25-hga*.12;awayScore+=ag*.25-aga*.12;base.push(`Temporada: ${home} marcou ${hg||'-'} e sofreu ${hga||'-'}; ${away} marcou ${ag||'-'} e sofreu ${aga||'-'}.`); if(hg>ag)reasonsHome.push('melhor produção ofensiva na temporada'); if(ag>hg)reasonsAway.push('melhor produção ofensiva na temporada');}
 const internal=internalNotes(game); homeScore+=internal.homeBoost;awayScore+=internal.awayBoost; if(internal.notes.length){evidence++;base.push(...internal.notes);} if(internal.homeBoost)reasonsHome.push('contexto histórico favorável'); if(internal.awayBoost)reasonsAway.push('contexto histórico favorável'); if(ctx.news.needHome||ctx.news.pressureHome){homeScore+=7;reasonsHome.push('necessidade/pressão por resultado detectada em notícias');evidence+=0.5;} if(ctx.news.needAway||ctx.news.pressureAway){awayScore+=7;reasonsAway.push('necessidade/pressão por resultado detectada em notícias');evidence+=0.5;} for(const b of ctx.news.base||[])base.push(b); for(const b of ctx.weather.base||[])base.push(b);
 const canAssert=evidence>=2,leader=homeScore>=awayScore?home:away; const winPctHome=Math.max(15,Math.min(75,Math.round(50+(homeScore-awayScore)*1.2))); const winPctAway=100-winPctHome; let confidence=evidence>=5?'Alta':evidence>=3?'Moderada':evidence>=2?'Baixa+':'Baixa'; if(internal.rivalry&&confidence==='Alta')confidence='Moderada'; const winnerReasons=leader===home?reasonsHome:reasonsAway; const predictions=[{key:'winner',label:`${leader} aparece com melhor tendência de vitória`,target:leader,status:'pending'},{key:'pressure',label:`${leader} tende a pressionar mais`,target:leader,status:'pending'},{key:'shots',label:`${leader} tende a ter mais finalizações`,target:leader,status:'pending'},{key:'corners',label:`${leader} tende a gerar mais escanteios`,target:leader,status:'pending'},...winnerReasons.slice(0,4).map((r,i)=>({key:`reason_${i}`,label:r,target:leader,status:'neutral'}))]; return {hasEnoughData:canAssert,confidence,evidenceCount:evidence,homeContextScore:Math.round(homeScore),awayContextScore:Math.round(awayScore),pressureTeam:canAssert?leader:'',probableWinner:canAssert?leader:'',winPctHome,winPctAway,predictions,reading:canAssert?`${leader} aparece melhor no contexto pré-jogo com base nas fontes disponíveis.`:'Dados reais insuficientes para afirmar tendência pré-jogo.',base:base.length?base:['Sem base real suficiente para tendência pré-jogo.']}; }
function makeLive(stats,game,pregame){ const t=splitByTeam(stats),hs=t.homeStats,as=t.awayStats; const homeName=game.home?.name||t.home,awayName=game.away?.name||t.away; const finalHome=num(find(hs,['total shots','shots total'])),finalAway=num(find(as,['total shots','shots total'])),targetHome=num(find(hs,['shots on goal','shots on target'])),targetAway=num(find(as,['shots on goal','shots on target'])),cornerHome=num(find(hs,['corner'])),cornerAway=num(find(as,['corner'])),possHome=num(find(hs,['ball possession','possession'])),possAway=num(find(as,['ball possession','possession'])); const has=!!(finalHome||finalAway||targetHome||targetAway||cornerHome||cornerAway||possHome||possAway); if(!has)return null; const hp=finalHome*2+targetHome*4+cornerHome*2+possHome*.25,ap=finalAway*2+targetAway*4+cornerAway*2+possAway*.25; const leader=hp>=ap?homeName:awayName; const updatedPredictions=(pregame.predictions||[]).map(p=>{ if(p.key==='winner'){const hsco=num(game.home.score),asco=num(game.away.score); if(hsco===asco)return {...p,status:'pending'}; const winning=hsco>asco?homeName:awayName; return {...p,status:winning===p.target?'good':'bad'};} if(p.key==='pressure')return {...p,status:leader===p.target?'good':'bad'}; if(p.key==='shots'){const shotLeader=finalHome===finalAway?'':(finalHome>finalAway?homeName:awayName); return {...p,status:shotLeader?(shotLeader===p.target?'good':'bad'):'pending'};} if(p.key==='corners'){const cornerLeader=cornerHome===cornerAway?'':(cornerHome>cornerAway?homeName:awayName); return {...p,status:cornerLeader?(cornerLeader===p.target?'good':'bad'):'pending'};} return p; }); return {dataType:'live',hasEnoughData:true,confidence:(finalHome+finalAway+cornerHome+cornerAway)>=10?'Alta':'Moderada',reading:`${leader} pressiona mais neste momento com base nas estatísticas ao vivo.`,pressureTeam:leader,predictions:updatedPredictions,predictionScore:{good:updatedPredictions.filter(p=>p.status==='good').length,bad:updatedPredictions.filter(p=>p.status==='bad').length,total:updatedPredictions.filter(p=>['good','bad'].includes(p.status)).length},finalizations:{home:finalHome,away:finalAway},shotsOnGoal:{home:targetHome,away:targetAway},corners:{home:cornerHome,away:cornerAway},possession:{home:possHome,away:possAway},base:[`Finalizações ao vivo: ${finalHome} x ${finalAway}.`,`Chutes no gol ao vivo: ${targetHome} x ${targetAway}.`,`Escanteios ao vivo: ${cornerHome} x ${cornerAway}.`,`Posse ao vivo: ${possHome||'-'}% x ${possAway||'-'}%.`]}; }
function topShooters(players){ const rows=[]; for(const p of players||[]){const player=p.player?.name||'',stats=p.statistics?.[0]||{},shots=num(stats.shots?.total),on=num(stats.shots?.on),goals=num(stats.goals?.total); if(player&&(shots||on||goals))rows.push({player,shots,on,goals});} return rows.sort((a,b)=>b.shots-a.shots).slice(0,8); }
app.get('/api/game-details',async(req,res)=>{ try{ const fixtureId=req.query.fixtureId; const game=req.query.game?JSON.parse(req.query.game):null; let teamStats=[],events=[]; if(fixtureId){const [statsJson,eventsJson]=await Promise.all([safeApiFootball(`/fixtures/statistics?fixture=${fixtureId}`),safeApiFootball(`/fixtures/events?fixture=${fixtureId}`)]); teamStats=normalizeStats(statsJson.response);events=normalizeEvents(eventsJson.response);} let pregame,playersHome=[],playersAway=[]; const news=await newsContext(game); const weather=await weatherContext(game); if(game?.home?.id&&game?.away?.id){ const homeId=game.home.id,awayId=game.away.id,leagueId=game.leagueId,season=game.season; const [hr,ar,hhr,aar,h2h,standings,hs,ass,ph,pa]=await Promise.all([getTeamRecent(homeId,null,10),getTeamRecent(awayId,null,10),getTeamRecent(homeId,'home',10),getTeamRecent(awayId,'away',10),getH2H(homeId,awayId),getStandings(leagueId,season),getTeamSeasonStats(homeId,leagueId,season),getTeamSeasonStats(awayId,leagueId,season),getPlayerSeasonStats(homeId,leagueId,season),getPlayerSeasonStats(awayId,leagueId,season)]); playersHome=topShooters(ph);playersAway=topShooters(pa); pregame=makePregame(game,{homeRecent:teamRecentSummary(hr,homeId),awayRecent:teamRecentSummary(ar,awayId),homeHomeRecent:teamRecentSummary(hhr,homeId),awayAwayRecent:teamRecentSummary(aar,awayId),h2h,homeStanding:standingOf(standings,homeId),awayStanding:standingOf(standings,awayId),homeSeasonStats:hs,awaySeasonStats:ass,news,weather}); if(playersHome.length||playersAway.length)pregame.base.push('Jogadores: principais finalizadores carregados.'); } else { pregame={hasEnoughData:false,confidence:'Baixa',evidenceCount:0,pressureTeam:'',probableWinner:'',reading:'Esse jogo não possui IDs suficientes para montar contexto real.',predictions:[],base:['Sem IDs de time/competição suficientes.',...news.base,...weather.base]}; } const live=makeLive(teamStats,game,pregame); const trend={dataType:'trend',hasEnoughData:pregame.hasEnoughData,confidence:pregame.confidence,reading:pregame.hasEnoughData?`Tendência contextual: ${pregame.probableWinner} aparece como provável melhor cenário.`:'Sem dados reais suficientes para tendência.',pressureTeam:pregame.pressureTeam||'',predictions:pregame.predictions||[],base:pregame.base||[]}; const analysis={live:live||{dataType:'none',hasEnoughData:false,reading:'Sem estatísticas ao vivo suficientes.',predictions:pregame.predictions||[]},trend,pregame,displayStats:live||null,contextSource:'Context Engine V17',main:live||trend}; res.json({ok:true,fixtureId:fixtureId||'',teamStats,events,players:{home:playersHome,away:playersAway},news:news.items||[],weather:weather.data,analysis}); }catch(e){res.status(500).json({ok:false,error:String(e.message||e)});} });
app.listen(PORT,()=>console.log('DhuniorStats V17 Prováveis Vencedores rodando na porta '+PORT));
